import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/providers";
import '@ant-design/v5-patch-for-react-19';
import TopNavbar from "@/components/navBar/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const getActualYear = () => {
    return new Date().getFullYear();
  };

  return (
    <html lang="en">
      <body
        className= "flex flex-col min-h-screen bg-gradient-to-r bg-gray-100"
      >
        <Providers>
          <header>
          <TopNavbar />
          </header>
        <main className="flex flex-col flex-grow items-center justify-center text-black p-5">
            {children}
          </main>
          <footer className="border-t border-gray-400 text-gray-400 py-4 text-center sticky bottom-0">
            <p>© {getActualYear()} User App</p>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
